# Generated by Django 6.1.1 on 2026-09-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='purpose',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
